[build]
command = "pnpm run build"
publish = "."

[context.production]
command = "NODE_ENV=production pnpm run db:migrate && pnpm run build"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

