-- Intentionally empty.
--
-- The Postgres docker-compose service mounts this file as
-- `/docker-entrypoint-initdb.d/init.sql` so the DB has *something*
-- to run on first boot. The schema itself lives in `db/migrations/`
-- and is applied via `dbmate up` from the Server's `npm run db:migrate`
-- script — keeping the schema in one place (the migration history)
-- avoids drift between this bootstrap file and the canonical state.
