#!/bin/bash

# Script to generate migrations automatically using migra
# Compares current DB schema with desired schema.prisma

set -e

MIGRATION_NAME=$1

if [ -z "$MIGRATION_NAME" ]; then
  echo "❌ You must provide a migration name"
  echo "Usage: ./scripts/migrate-auto.sh migration_name"
  exit 1
fi

# Load environment variables
if [ -f .env ]; then
  export $(cat .env | tr -d '\r' | grep -v '^#' | xargs)
fi

if [ -z "$DATABASE_URL" ]; then
  echo "❌ DATABASE_URL is not set in .env"
  exit 1
fi

# Check that migra is installed
if ! command -v migra &> /dev/null; then
  echo "❌ migra is not installed"
  echo "💡 Install with: pip3 install migra-maintained psycopg2-binary"
  exit 1
fi

# Create temporary database for desired schema (using Node + pg; no createdb/dropdb needed)
TEMP_DB_NAME="gymapp_migra_temp_$$"
TEMP_DB_URL="${DATABASE_URL/gymapp/$TEMP_DB_NAME}"

echo "📦 Creating temporary database for desired schema..."

# Drop temp DB if it exists from a previous run, then create it
node scripts/db-helper.mjs drop-db "$TEMP_DB_NAME" 2> /dev/null || true
node scripts/db-helper.mjs create-db "$TEMP_DB_NAME" || {
  echo "❌ Failed to create temporary database"
  exit 1
}

# Save original DATABASE_URL
ORIGINAL_DATABASE_URL="$DATABASE_URL"

# Apply Prisma schema directly to temporary DB (desired state)
echo "📋 Applying schema.prisma to temporary DB (desired state)..."
export DATABASE_URL="$TEMP_DB_URL"
npx prisma db push --schema=./prisma/schema.prisma --accept-data-loss || {
  echo "❌ Error applying schema from Prisma"
  export DATABASE_URL="$ORIGINAL_DATABASE_URL"
  node scripts/db-helper.mjs drop-db "$TEMP_DB_NAME" 2> /dev/null || true
  exit 1
}

# Restore original DATABASE_URL for comparison
# We compare: real DB (current state) vs temporary DB (desired state)
export DATABASE_URL="$ORIGINAL_DATABASE_URL"

# Compare schemas and generate migration
echo "🔍 Comparing schemas..."
# Use --unsafe so migra outputs SQL even when it includes destructive changes (e.g. DROP);
# always review the generated migration before applying
MIGRATION_SQL=$(migra "$DATABASE_URL" "$TEMP_DB_URL" --with-privileges --unsafe 2>&1 || true)

# Clean migra output (drop warnings, info, error lines; keep only SQL)
# Strip: drop constraint; alter column (set default|not null|data type) for existing columns — keep only additive changes e.g. add column
# Strip: anything touching schema_migrations (dbmate's table — never modify it)
CLEAN_SQL=$(echo "$MIGRATION_SQL" | grep -v "^WARNING" | grep -v "^INFO" | grep -v "ERROR:" | grep -v "destructive" | grep -v "Use the --unsafe" | grep -v "drop constraint" | grep -v 'alter column.*set default' | grep -v 'alter column.*set not null' | grep -v 'alter column.*set data type' | grep -v "schema_migrations" | sed '/^$/d')

# Normalise SQL keywords to uppercase (ALTER, TABLE, ADD COLUMN, DROP COLUMN, DEFAULT, etc.)
CLEAN_SQL=$(echo "$CLEAN_SQL" | sed \
  -e 's/^alter /ALTER /g' \
  -e 's/ add column / ADD COLUMN /g' \
  -e 's/ drop column / DROP COLUMN /g' \
  -e 's/ table / TABLE /g' \
  -e 's/ default / DEFAULT /g' \
  -e 's/ not null/ NOT NULL/g' \
  -e 's/ primary key/ PRIMARY KEY/g' \
  -e 's/ unique / UNIQUE /g' \
  -e 's/ references / REFERENCES /g' \
  -e 's/ on delete / ON DELETE /g' \
  -e 's/ on update / ON UPDATE /g' \
  -e 's/ constraint / CONSTRAINT /g' \
  -e 's/ create index / CREATE INDEX /g' \
  -e 's/ create unique index / CREATE UNIQUE INDEX /g' \
  -e 's/ using / USING /g')

if [ -z "$CLEAN_SQL" ] || echo "$CLEAN_SQL" | grep -q "Nothing to do"; then
  echo "⚠️  No differences between schemas"
  echo "💡 Current schema already matches schema.prisma"

  # Cleanup
  node scripts/db-helper.mjs drop-db "$TEMP_DB_NAME" 2> /dev/null || true
  exit 0
fi

# Create new migration with dbmate
echo "📝 Creating migration: $MIGRATION_NAME..."
npx dbmate new "$MIGRATION_NAME"

# Find the newly created migration file
MIGRATION_FILE=$(ls -t db/migrations/*${MIGRATION_NAME}*.sql 2> /dev/null | head -1)

if [ -z "$MIGRATION_FILE" ]; then
  echo "❌ Could not find migration file"
  node scripts/db-helper.mjs drop-db "$TEMP_DB_NAME" 2> /dev/null || true
  exit 1
fi

# Idempotent up: ADD COLUMN -> ADD COLUMN IF NOT EXISTS
UP_SQL=$(echo "$CLEAN_SQL" | sed 's/ADD COLUMN "/ADD COLUMN IF NOT EXISTS "/g')

# Generate rollback (migrate:down): ADD COLUMN "x" ... -> DROP COLUMN IF EXISTS "x"
DOWN_SQL=$(echo "$CLEAN_SQL" | sed 's/ADD COLUMN "\([^"]*\)".*$/DROP COLUMN IF EXISTS "\1";/g')
# If no ADD COLUMN was present, keep placeholder
if [ -z "$DOWN_SQL" ] || [ "$DOWN_SQL" = "$CLEAN_SQL" ]; then
  DOWN_SQL="-- Revert changes manually if needed
-- Review the SQL above to create the appropriate rollback"
fi

# Write SQL generated by migra
cat > "$MIGRATION_FILE" << EOF
-- migrate:up
$UP_SQL

-- migrate:down
$DOWN_SQL
EOF

echo "✅ Migration generated automatically: $MIGRATION_FILE"
echo ""
echo "📋 Generated SQL:"
echo "$UP_SQL"
echo ""
echo "⚠️  IMPORTANT: Review the migration before applying!"
echo "💡 Apply with: npm run db:migrate"

# Clean up temporary database
node scripts/db-helper.mjs drop-db "$TEMP_DB_NAME" 2> /dev/null || true
